FROM python:3.12-slim

WORKDIR /app

RUN apt update \
    && apt install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh -s -- --no-modify-path
ENV PATH="/root/.local/bin:$PATH"


COPY . /app/
RUN uv sync --frozen

CMD [ "uv", "run", "python", "run.py" ]