FROM python:3.13-alpine

WORKDIR /app

RUN apk add --no-cache curl

RUN curl -LsSf https://astral.sh/uv/install.sh | sh -s -- --no-modify-path
ENV PATH="/root/.local/bin:$PATH"

COPY . /app/
RUN uv sync --frozen

CMD [ "uv", "run", "python", "run.py" ]