apiVersion: v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: kg-ai-app
  namespace: abhijit
spec:
  selector:
    matchLabels:
      app: kg-ai-app
  template:
    metadata:
      labels:
        app: kg-ai-app
    spec:
      containers:
      - name: kg-ai-app
        image: <Image>
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
